# ╔══════════════════════════════════════════════════════════════╗
# ║                             TChat                            ║
# ║                      tect.host | by Alex                     ║
# ║                                                              ║
# ║                          config.yml                          ║
# ╚══════════════════════════════════════════════════════════════╝

# DON'T TOUCH THIS!
config-version: 5

chat:
  # Global chat format (modules.format)
  # You can use placeholders from the PlaceholderAPI
  # Preferably use MiniMessage colors, although legacy colors (&) will also work
  format: "%luckperms_prefix%&r&a%player_name% &e>> &7<message>"

  # Language file to use for plugin messages
  # Place your file in /lang/ folder (e.g. fr.yml)
  # Available: en.yml | es.yml
  lang: "en.yml"


# Methods
#   Local databases:
#    - SQLite
storage:
  method: SQLite
  remote:
    host: localhost
    port: 3306
    database: tchat
    username: root
    password: ""


# If the value is false, the module will not be instantiated, will not load its own configuration
# and will not participate in the chat flow at all (you can also delete its corresponding configuration file)
modules:

  # Detects and blocks/censors IP addresses, domain names and URLs in chat
  #
  # Anti advertising module loaded from modules/antiadvertising.yml
  anti-advertising: true

  # It lets censor, block, or convert words to
  # lowercase when they're typed in all caps
  #
  # Anti cap module loaded from modules/anticap.yml
  anti-cap: true

  # This module sends messages via chat (or performs actions) every few seconds
  #
  # Auto broadcast module loaded from modules/autobroadcast.yml
  auto-broadcast: true

  # This module adds a command to block the chat
  #
  # This module does not have a configuration file
  block-chat: true

  # Allows to block specific commands from being used in chat
  #
  # Blocked commands module loaded from modules/blockedcommands.yml
  blocked-commands: true

  # Allows to block or censor words from a list
  # It also detects similar words, for example:
  # If the word "hello" is blocked, "he llo" will also be blocked.
  #
  # Blocked words module loaded from modules/blockedwords.yml
  blocked-words: true

  # This module allows you to create private channels.
  #
  # Channels module loaded from modules/channels.yml
  channels: true

  # This module allows you to create channels between worlds
  #
  # Chat bridge module loaded from modules/chatbridge.yml
  chat-bridge: false

  # Allows players to display custom tags in chat
  #
  # Item tag module loaded from modules/chatplaceholders/chatplaceholders.yml
  chat-placeholders: true

  # Allows to translate colors and formats in chat using permissions
  #
  # This module does not have a configuration file
  colorchat: true

  # Global format module (The group format will continue working even if you disable this module)
  #
  # The format module applies to all users, if used in conjunction with the groups module,
  # it will only apply if the user's group does not have the format enabled
  #
  # Format module loaded from config.yml (do not delete this if you disable the format module)
  format: true

  # Allows you to configure prefixes, suffixes, formats, and other options by permission-based groups
  #
  # Group module loaded from modules/groups.yml
  group: true

  # Allows to inspect other player inventories
  #
  # Invsee module loaded from modules/invsee.yml
  invsee: false

  # Allows to change your nickname
  #
  # This module does not have a configuration file
  nick: true

  # Send a message to the admins via chat when the plugin isn't up to date
  #
  # This module does not have a configuration file
  update-notify: true

  # This module allows you to use local chats (radius)
  # It also lets you block chat by world
  #
  # Worlds module loaded from modules/worlds.yml
  worlds: false
